% !Rnw weave = knitr
% Initial stuff
\section{Initial Stuff}
\label{sec:initial}
The data is as described in Section ~\ref{sec:thedata}.

We examined the answer to the question``What percentage of rice crops were lost due to the flood?''  We then randomly chose five Tehsils from each province, then 10, then 15 and performed the same analysis on the reduced data.

In situations where a province has fewer than five, 10 or 15 Tehsils sampled, all were used.
